### ISSUE TITLE
Currency sync has stopped working

### ISSUE THREAD

**Issue by fastknight** [Athenodoros/TopHat#13]
I'm getting a green tick for my API key - but it is definitely not syncing rates correctly. Sync says completed 0 minutes ago but balances never update. :(

Thanks!

**Comment by Athenodoros** [comment]
Took me a while, but I got there: looks like the currency rates were correct, but the balances weren't being aggregated up correctly. Next time you load it up (you'll need to close all existing tabs first) it should fix itself, and be good from now - let me know if there are any further issues!

Thanks for letting me know!

**Comment by fastknight** [comment]
Awesome - thank you :)

Really enjoy using this tool - thank you for publishing it.

**Comment by fastknight** [comment]
Spoke too soon. Exported data and re-imported to a new instance and balances are still not showing the correct conversions unfortunately.

**Comment by Athenodoros** [comment]
That's very weird - I'm not sure after some poking around what the issue could be. Couple of things that you could check which might help me pinpoint the issue:
- If you go to the accounts page and break down the summary by currency, are the totals correct in the original currencies? Are they being converted incorrectly there? Is the rate obviously something different (eg. prior to the fix above it was using the conversion rate at the time of the transaction, rather than the current one - maybe you're still running a version which does that)?
- I've just added a table schema version on the debug page in the settings menu - can you check that it's upgraded from 2 to 3 (which should automatically recalculate everything using the latest rates)? If you're still having problems, are they fixed by refreshing the caches using the button on that page?

**Comment by fastknight** [comment]
It does appear to be refreshing now - I don't know whats different though!

I can see debug information and schema is at 3 on both instances I was testing.

I will keep an eye on it. Might be nice if the active exchange rate could be viewed somewhere maybe. Thanks for looking into it!

10 May 2022, 03:32 by ***@***.***:

**Comment by Athenodoros** [comment]
Makes sense - I've added some tooltips, hopefully that helps. Glad you're enjoying it!
